nginx:
  container_name: nginx
  image: nginx
  ports:
    - "8081:80"
  volumes:
    - ./docker/nginx/etc/nginx:/etc/nginx
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    - ./:/var/www/html

  links:
    - php

php:
  container_name: php
  build: ./docker/php
  ports:
    - "9000:9000"
  volumes:
    - ./:/var/www/html
  #links:
   # - mysql

mysqlyii:
  container_name: mysqlyii
  image: mysql:5.6.22
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    #- MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=casasdap_casas
  cap_add:
    - SYS_NICE
  volumes:
    - ./docker/mysql/var/lib/mysql:/var/lib/mysql
    - ./docker/mysql/docker-entrypoint-initdb.d:/test
