version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8081:80'
   
    links:
      - php
  php:
    container_name: php
    tty: true
    build: 
      context: . 
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000:9000'

    links:
     - mysql
  mysql:
    container_name: mysql
    #image: 'mysql:5.6.22'
    image: 'mariadb:10.6.4-focal'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=casasdap_casas
    cap_add:
      - SYS_NICE
    volumes:
      - '.docker/mysql/var/lib/mysql:/var/lib/mysql'
      - 'service-data:/var/lib/mysql'
   
