<?php

require_once dirname(__FILE__) . '/../../../../models/Proprietario.php';

/**
 * Test class for Proprietario.
 * Generated by PHPUnit on 2012-01-28 at 01:43:38.
 */
class ProprietarioTest extends PHPUnit_Framework_TestCase {
   /**
     * @var Proprietario
     */
    protected $object;
   /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Proprietario;
    }
   /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
   }
   /**
     * @covers Proprietario::model
     * @todo Implement testModel().
     */
    public function testModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::tableName
     * @todo Implement testTableName().
     */
    public function testTableName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::rules
     * @todo Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::relations
     * @todo Implement testRelations().
     */
    public function testRelations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::attributeLabels
     * @todo Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::search
     * @todo Implement testSearch().
     */
    public function testSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::validatePassword
     * @todo Implement testValidatePassword().
     */
    public function testValidatePassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::hashPassword
     * @todo Implement testHashPassword().
     */
    public function testHashPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::validatePassword2
     * @todo Implement testValidatePassword2().
     */
    public function testValidatePassword2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
   /**
     * @covers Proprietario::hashPassword2
     * @todo Implement testHashPassword2().
     */
    public function testHashPassword2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
