<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A sua reserva foi actualizada!' => '',
  'A sua reserva foi suplantada!' => '',
  'Casas do seu alerta' => '',
  'Confirmação de registo' => '',
  'Confirmação de registo!' => '',
  'Confirme o seu registo!' => '',
  'Confirme o seu registo.' => '',
  'Lembrete Pagamento pre reserva ' => '',
  'Lembrete para atribuir feedback reserva ' => '',
  'O seu imóvel foi reservado!' => '',
  'O seu imóvel tem uma actualização de reserva!' => '',
  'Obrigado pela sua Reserva!' => '',
  'Pedido de informação' => '',
  'Reserva ' => '',
);
